var audioFiles = [
	"bounce1.mp3",
	"engine1.mp3",
	"explosion1.mp3",
	"hit1.mp3",
	"hit2.mp3",
	"hit3.mp3",
	"shot1.mp3",
	"shot2.mp3",
	"shot_light_high pitch.mp3",
	"theme1.mp3",
	"theme_central.mp3",
	"theme_imperial.mp3",
	"theme_omar.mp3",
	"theme_outer.mp3",
]